config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :messages, only: [:create, :index]
  end

  root to: 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :messages, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :username

  protect_from_forgery with: :exception

  before_filter :set_username

  protected

  def set_username
    if params[:username].present?
      session[:username] = params[:username]
      redirect_to request.path
    end
  end

  def username
    session[:username] || 'Anonimo'
  end

end

app/controllers/messages_controller.rb
 class MessagesController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @messages = @post.messages.order(created_at: :asc).last(50)

    respond_to do |format|
      format.html
      format.json do
        render json: @messages
      end
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @message = @post.messages.create!(message_params)
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(username: username)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
  <head>

    <title>Webinário Organizze</title>

    <!-- CSS -->
    <%= stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track' => true %>

    <!-- JS -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>

  </head>

  <body class='site webinars-show'>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!-- Header -->
    <header class="header" data-header>
      <div class="row">

        <div class="col-md-2 col-xs-2 left">
          <a href="/">
            <h1>Webinário Organizze</h1>
          </a>
        </div>

        <div class="col-xs-8 center">
          <nav class="navigation">
            <ul>
              <li><a href="#">Análise</a></li>
            </ul>
          </nav>
        </div>

        <div class="col-xs-2 right">
          <div class="settings">
            <ul>
              <li><a href="#">Configurações</a></li>
              <li><a href="#">Sair</a></li>
            </ul>
          </div>
        </div>

      </div>
    </header>

    <!-- Conteúdo -->
    <section class="content" data-content>
      <%= yield %>
    </section>

  </body>
</html>

app/views/messages/create.js.erb
$("#new_message")[0].reset();

app/views/messages/index.html.erb
<h1>Chat window</h1>

<div class="chat-container">
  <div class="group-chat">
    <ul class="chat">
    </ul>
  </div>

  <%= form_for Message.new, remote: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit 'Enviar' %>
  <% end %>
</div>

<%#= render @messages %>

<script type="text/javascript">
  $(function() {

    function request() {

      var $url = "<%= messages_list_path %>.json";

      $.ajax($url, {
        success: function(data) {
          // console.log(data);

          var messages = [];

          $.each(data, function( key, val ) {
            messages.push( "<li id='" + key + "'>" + val.content + "</li>" );
          });

          $('.chat').html(messages)

        },
        error: function() {
          console.log('Ocorreu um erro');
        }
      });

      setTimeout(request, 1000);
    }

    request();

    setTimeout(function(){
      $('.chat').scrollTop($('.chat')[0].scrollHeight);
    }, 100);

  });
</script>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="main" data-main>
  <iframe class="video" frameborder="0" allowfullscreen="1" src="https://www.youtube.com/embed/Ti802LgPRkE?autoplay=0&amp;controls=0&amp;rel=0&amp;showinfo=0&amp;autohide=1&amp;hd=1&amp;modestbranding=0"></iframe>
  <div class="overlay"></div>
</div>

<aside class="side-bar" data-sidebar>
  <div class="chat-container">

    <ul class="chat">
    </ul>

    <% if username != 'Anonimo' %>

      <%= form_for [@post, Message.new], remote: true do |f| %>
        <%= f.text_field :content, placeholder: 'Conteudo' %>
        <%= f.submit 'Enviar', class: 'button' %>
      <% end %>

    <% else %>

      <%= form_tag request.path, method: :get do %>
        <%= text_field_tag :username, '', placeholder: 'Username' %>
        <%= submit_tag 'Enviar', class: 'button' %>
      <% end %>

    <% end %>

  </div>
</aside>

<script type="text/javascript">
  $(function() {

    function request() {

      var $url = "<%= post_messages_path(@post, format: :json) %>";

      $.ajax($url, {
        success: function(data) {
          // console.log(data);

          var messages = [];

          $.each(data, function( key, val ) {
            messages.push( "<li id='" + key + "'><span>" + val.username + "</span> - " + val.content + "</li>" );
          });

          $('.chat').html(messages)

        },
        error: function() {
          console.log('Ocorreu um erro');
        }
      });

      // setTimeout(request, 1000);
    }

    request();

    setTimeout(function(){
      $('.chat').scrollTop($('.chat')[0].scrollHeight);
    }, 100);

    // $('.button').on('click', function(e){
    //   if(!$('#message_content').val()) {
    //     alert('O campo não pode estar vazio');
    //     return false;
    //   }
    // });

  });
</script>